### ISSUE TITLE
When I step on the pedal, the car still prompts me to place the nfc card, what should I do?

### ISSUE THREAD

**Issue by zhy2020** [kaedenbrinkman/PyTeslaBLE#6]
Hello, I am having a problem, when I add the key to the whitelist, I can unlock the vehicle normally. But when I step on the pedal, the car still prompts me to place the nfc card, what should I do?
![51cba5ae718d4caf1e4072a6d11b7b3](https://github.com/kaedenbrinkman/PyTeslaBLE/assets/61862986/edc52e0d-e469-415b-a219-39ae164311f2)

**Comment by 4UI** [comment]
Hi，我也在试这个代码，不过我卡在添加白名单可以成功，但是没法操控，是否方便告知一下如何调通的，是否可以方便加一下微信: i10034 ，非常感谢。
